# Import numpy module
# Create numpy array manually

In [1]:
import numpy as np

In [11]:
#create a 1D numpy array
a= np.array([1,2,3])
print('1D numpy array:', a)

#create a 2D numpy array
b= np.array([[1,2,3], [4,5,6]])
print('2D numpy array:', b)

#one more variation in creating 2D numpy array
c= np.array(([1,2,3], [4,5,6]))
print('2D numpy array:', c)

#creating numpy array with specific datatype
d= np.array([[1,2,3],[4,5,6]], dtype=float)
print('2D numpy array with datatype specified:', d)

1D numpy array: [1 2 3]
2D numpy array: [[1 2 3]
 [4 5 6]]
2D numpy array: [[1 2 3]
 [4 5 6]]
2D numpy array with datatype specified: [[1. 2. 3.]
 [4. 5. 6.]]


# Basic array analysis

In [16]:
#Knowing array dimention, shape, size, datatype, itemsize, data
print('dim: {}, shape: {}, size: {}, datatype: {}, itemsize: {}, data: {}'.format(b.ndim, b.shape, b.size, b.dtype, b.itemsize, b.data))

dim: 2, shape: (2, 3), size: 6, datatype: int64, itemsize: 8, data: <memory at 0x7fc868042630>


# FNF numpy array creation :)

In [33]:
#creat an array giving upper bound
x= np.arange(10)
print('arange(10): {}'.format(x))

#creat array given range
xrange= np.arange(2, 12)
print('arange(2, 12): {}'.format(xrange))

#create array given range and interval
x= np.arange(2, 12, 2)
print('arrange(2,12,2): {}'.format(x))

x= np.arange(2, 12, 0.3)
print('arrange(2,12,0.3): {}'.format(x))

#Specify only certain length of array then we can use linespace function
x= np.linspace(2,12,3)
print('linspace(2,12,3): {}'.format(x))

#create an array with zeros
x= np.zeros((2,3))
print('zeros((2,3)): {}'.format(x))

#create an array with ones
x= np.ones((2,3))
print('ones((2,3)): {}'.format(x))

x= np.ones_like(x)
print('ones_like(x): {}'.format(x))

#reshape an array
z= np.zeros(100).reshape((10,10))
print('zeros(100).reshape((10,10)): {}'.format(z))

arange(10): [0 1 2 3 4 5 6 7 8 9]
arange(2, 12): [ 2  3  4  5  6  7  8  9 10 11]
arrange(2,12,2): [ 2  4  6  8 10]
arrange(2,12,0.3): [ 2.   2.3  2.6  2.9  3.2  3.5  3.8  4.1  4.4  4.7  5.   5.3  5.6  5.9
  6.2  6.5  6.8  7.1  7.4  7.7  8.   8.3  8.6  8.9  9.2  9.5  9.8 10.1
 10.4 10.7 11.  11.3 11.6 11.9]
linspace(2,12,3): [ 2.  7. 12.]
zeros((2,3)): [[0. 0. 0.]
 [0. 0. 0.]]
ones((2,3)): [[1. 1. 1.]
 [1. 1. 1.]]
ones_like(x): [[1. 1. 1.]
 [1. 1. 1.]]
zeros(100).reshape((10,10)): [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
